name: website

on:
 push:
   branches: [main]
 workflow_dispatch:

permissions: 
 pages: write
 id-token: write

jobs:
  deployments:
   runs-on: ubuntu-latest

   steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: setup pages
       uses: actions/configure-pages@v4

     - name: static pages
       uses: actions/upload-pages-artifact@v4

     - name: deploy
       uses: actions/deploy-pages@v4
